### PR TITLE
[Android/Guava] fix for missing [assembly:TargetFramework]

### LINKED ISSUE #3343: WorkManager fails to compile on version 9.4
### Steps to Reproduce

1. Checkout https://github.com/jschmid/WorkManagerCompilation
2. Try to compile

### Expected Behavior

Project compiles, like on Xamarin.Android 9.3.

### Actual Behavior

Compilation error:

```
Target _CompileJava:
    Directory "obj/Debug/android/bin/classes" doesn't exist. Skipping.
    /Users/jonas/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/javac -J-Dfile.encoding=UTF8 -d obj/Debug/android/bin/classes -classpath /Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v9.0/mono.android.jar:/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/java_runtime_fastdev.jar:obj/Debug/lp/0/jl/formsviewgroup.jar:obj/Debug/lp/1/jl/android.arch.core.common.jar:obj/Debug/lp/10/jl/bin/classes.jar:obj/Debug/lp/11/jl/com.android.support.collections.jar:obj/Debug/lp/12/jl/bin/classes.jar:obj/Debug/lp/13/jl/bin/classes.jar:obj/Debug/lp/14/jl/bin/classes.jar:obj/Debug/lp/15/jl/bin/classes.jar:obj/Debug/lp/16/jl/bin/classes.jar:obj/Debug/lp/17/jl/bin/classes.jar:obj/Debug/lp/18/jl/bin/classes.jar:obj/Debug/lp/19/jl/bin/classes.jar:obj/Debug/lp/2/jl/bin/classes.jar:obj/Debug/lp/20/jl/bin/classes.jar:obj/Debug/lp/21/jl/bin/classes.jar:obj/Debug/lp/22/jl/bin/classes.jar:obj/Debug/lp/23/jl/bin/classes.jar:obj/Debug/lp/24/jl/bin/classes.jar:obj/Debug/lp/25/jl/bin/classes.jar:obj/Debug/lp/26/jl/bin/classes.jar:obj/Debug/lp/27/jl/bin/classes.jar:obj/Debug/lp/28/jl/bin/classes.jar:obj/Debug/lp/29/jl/bin/classes.jar:obj/Debug/lp/3/jl/android.arch.lifecycle.common.jar:obj/Debug/lp/30/jl/bin/classes.jar:obj/Debug/lp/32/jl/bin/classes.jar:obj/Debug/lp/33/jl/bin/classes.jar:obj/Debug/lp/34/jl/bin/classes.jar:obj/Debug/lp/35/jl/bin/classes.jar:obj/Debug/lp/36/jl/bin/classes.jar:obj/Debug/lp/37/jl/bin/classes.jar:obj/Debug/lp/38/jl/bin/classes.jar:obj/Debug/lp/39/jl/bin/classes.jar:obj/Debug/lp/4/jl/bin/classes.jar:obj/Debug/lp/43/jl/bin/classes.jar:obj/Debug/lp/44/jl/bin/classes.jar:obj/Debug/lp/45/jl/bin/classes.jar:obj/Debug/lp/46/jl/common.jar:obj/Debug/lp/47/jl/bin/classes.jar:obj/Debug/lp/48/jl/bin/classes.jar:obj/Debug/lp/5/jl/bin/classes.jar:obj/Debug/lp/6/jl/bin/classes.jar:obj/Debug/lp/7/jl/bin/classes.jar:obj/Debug/lp/8/jl/bin/classes.jar:obj/Debug/lp/9/jl/com.android.support.support-annotations.jar -bootclasspath /Users/jonas/Library/Android/sdk/platforms/android-28/android.jar -encoding UTF-8 "@/var/folders/c8/w1k_9css1p17lw9288pp0bfw0000gn/T/tmp19026bba.tmp" 
    obj/Debug/android/src/md59c73ed0f6f0816547049fec1b3c815af/CalculatorWorker.java:4: error: cannot access ListenableFuture
    public class CalculatorWorker
           ^
      class file for com.google.common.util.concurrent.ListenableFuture not found
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    1 error
    obj/Debug/android/src/md59c73ed0f6f0816547049fec1b3c815af/CalculatorWorker.java(4,8): error :  error: cannot access ListenableFuture
    obj/Debug/android/src/md59c73ed0f6f0816547049fec1b3c815af/CalculatorWorker.java(4,8): error : public class CalculatorWorker
    obj/Debug/android/src/md59c73ed0f6f0816547049fec1b3c815af/CalculatorWorker.java(4,8): error :   class file for com.google.common.util.concurrent.ListenableFuture not found
    obj/Debug/android/src/md59c73ed0f6f0816547049fec1b3c815af/CalculatorWorker.java(4,8): error : 
Done building target "_CompileJava" in project "WorkManagerCompilation.Android.csproj" -- FAILED.

Done building project "WorkManagerCompilation.Android.csproj" -- FAILED.

Build FAILED.
```

### Version Information

<details> 
  <summary>From Visual Studio for Mac</summary>
=== Visual Studio Community 2019 for Mac ===

Version 8.1.5 (build 9)
Installation UUID: c1e57dbd-db6c-4e43-9f30-8df655acc4c6
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.1.8
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.2.107
	2.1.504
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.0.34 (Visual Studio Community)
Commit: xamarin-android/d16-2/7cce305
Android SDK: /Users/jonas/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.0 rc1

Build Information: 
Mono: mono/mono/2019-02@c6edaa62f94
Java.Interop: xamarin/java.interop/d16-2@b2b2610
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@4f717b6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jonas/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Apple Developer Tools ===

Xcode 10.2 (14490.120)
Build 10E125

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801050009
Git revision: bd0ab28ba941b19b39322247db020dcd0fb305d0
Build date: 2019-07-03 17:15:21+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
</details>

Fun stuff, if you:

* Compile using version 9.3.0.23
* Quit Visual Studio
* Install 9.4.0.34
* Open the projet and run

It will work. But that's not very practical. ¯\_(ツ)_/¯

> VS bug [#948417](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948417)

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/xamarin/xamarin-android/issues/3343
Context: https://github.com/xamarin/xamarin-android/issues/3343#issuecomment-511589968
Context: https://github.com/xamarin/xamarin-android/pull/2934

In Visual Studio 2019 16.1, we added some performance improvements in
Xamarin.Android.

In cases of .NET assemblies that:

* Do not have `[assembly: TargetFramework ("MonoAndroid")]`
* Have no reference to `Mono.Android.dll`

Unfortunately, these two Guava projects fit into this category! They
include `<EmbeddedJar/>` but otherwise have no markings at all that
would indicate they are Xamarin.Android assemblies.

Reading the source code for MSBuild, I found that including a single
`@(Compile)` item solves the issue:

https://github.com/microsoft/msbuild/blob/0cd0e92a7243088977d31b56626b56d6116de016/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3341-L3344

    <ItemGroup Condition="'@(Compile)' != '' and '$(TargetFrameworkMonikerAssemblyAttributeText)' != ''">
      <Compile Include="$(TargetFrameworkMonikerAssemblyAttributesPath)"/>
    </ItemGroup>

As soon as I added an empty `*.cs` file to the projects,
`[assembly:TargetFramework]` appeared in the output assembly with the
necessary info.

This must be a weird corner case for MSBuild... I am not sure if there
is anything we can do on the Xamarin.Android side yet.

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
@Redth is this a NuGet package that would be easy to update?

The only possible thing I could do is look for any `*.jar` file that is an `EmbedddedResource` on the Xamarin.Android side -- which would hurt build performance slightly, but be better than reverting the improvement entirely.

Also... are there other components like these?

**Comment by dellis1972** [comment]
@jonathanpeppers this might be related to the issue I found https://github.com/xamarin/xamarin-android/pull/3354 ...

**Comment by dellis1972** [comment]
Would an AssembyInfo.cs file not be better? Surely the assembly should have version information right?

**Comment by jonathanpeppers** [comment]
@dellis1972 yeah I was seeing it put that file in the temp location, but things were working OK.

The problem was it doesn't create that file at all if `@(Compile)` is blank. These projects are special in that they don't have any code, and just have `<EmbeddedJar/>`.

> Would an AssembyInfo.cs file not be better? Surely the assembly should have version information right?

These are actually SDK-style projects, which don't have `AssemblyInfo.cs`:

https://github.com/xamarin/XamarinComponents/blob/54646f5c0bef9c618c700628bd1167768d7c9b4f/Android/Guava/source/Guava.ListenableFuture/Guava.ListenableFuture.csproj

**Comment by dellis1972** [comment]
@jonathanpeppers it might be just adding

```
<AssemblyVersion>1.0.0.0</AssemblyVersion>
```

or something is enough to get something into the `@(Compile)` itemgroup

**Comment by dellis1972** [comment]
@jonathanpeppers see https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#assemblyinfo-properties

**Comment by jonathanpeppers** [comment]
This is really weird, if I add those, I get:
```
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(/*Could not decode attribute arguments.*/)]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("\r\n    NOTE: This package is meant to be used as a reference only for other binding projects that depend on Guava.\r\n    This package does not expose any useful API's in the .dll itself.\r\n    \r\n    Guava is a set of core libraries that includes new collection types (such as multimap and multiset), immutable collections, a graph library, functional types, an in-memory cache, and APIs/utilities for concurrency, I/O, hashing, primitives, reflection, string processing, and much more!\r\n    ")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("Xamarin.Google.Guava.ListenableFuture")]
[assembly: AssemblyTitle("Xamarin.Google.Guava.ListenableFuture")]
[assembly: SecurityPermission(8, SkipVerification = true)]
[assembly: AssemblyVersion("1.0.0.0")]
[module: UnverifiableCode]
```
These attrributes come from: `obj\Release\monoandroid50\Guava.AssemblyInfo.cs`

But the one that is messed up here is: `C:\Users\jopepper\AppData\Local\Temp\MonoAndroid,Version=v5.0.AssemblyAttributes.cs` and it's not being added to `@(Compile)` unless there is at least one `@(Compile)` item already...

I should probably file an MSBuild bug.

**Comment by jonathanpeppers** [comment]
On second thought, we might be able to just fix this: https://github.com/xamarin/xamarin-android/compare/master...jonathanpeppers:workmanager

It is looking like it only adds ~25ms on _every_ build, but let me time that with a Release build of XA on a slower PC to be sure.

**Comment by dellis1972** [comment]
@jonathanpeppers interesting idea. I would make

`EmbeddedResourceExtension=".jar"`

support

`EmbeddedResourceExtensions=".jar;.zip;.mp4"`

so that we can extend it in the future.
